export const albumData = [
  {
    title: 'Rush',
    artist: 'Rush',
    releaseDate: '3/1/1974',
    recordLabel: 'Moon',
    peakChartPositionUS: 105,
    certification: 'Gold',
    albumType: 'Studio',
    unitsSold: 900000,
    url: 'https://www.rush.com/albums/rush/',
  },
  {
    title: 'Fly by Night',
    artist: 'Rush',
    releaseDate: '2/15/1975',
    recordLabel: 'Mercury',
    peakChartPositionUS: 113,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 2210000,
    url: 'https://www.rush.com/albums/fly-by-night/',
  },
  {
    title: 'Caress of Steel',
    artist: 'Rush',
    releaseDate: '9/24/1975',
    recordLabel: 'Mercury',
    peakChartPositionUS: 148,
    certification: 'Gold',
    albumType: 'Studio',
    unitsSold: 650000,
    url: 'https://www.rush.com/albums/caress-of-steel/',
  },
  {
    title: '2112',
    artist: 'Rush',
    releaseDate: '4/1/1976',
    recordLabel: 'Mercury',
    peakChartPositionUS: 61,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 1211200,
    url: 'https://www.rush.com/albums/2112/',
  },
  {
    title: 'A Farewell to Kings',
    artist: 'Rush',
    releaseDate: '9/1/1977',
    recordLabel: 'Mercury',
    peakChartPositionUS: 33,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 1100000,
    url: 'https://www.rush.com/albums/a-farewell-to-kings/',
  },
  {
    title: 'Hemispheres',
    artist: 'Rush',
    releaseDate: '10/29/1978',
    recordLabel: 'Mercury',
    peakChartPositionUS: 47,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 1350000,
    url: 'https://www.rush.com/albums/hemispheres/',
  },
  {
    title: 'Permanent Waves',
    artist: 'Rush',
    releaseDate: '2/14/1980',
    recordLabel: 'Mercury',
    peakChartPositionUS: 4,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 1200000,
    url: 'https://www.rush.com/albums/permanent-waves/',
  },
  {
    title: 'Moving Pictures',
    artist: 'Rush',
    releaseDate: '2/12/1981',
    recordLabel: 'Mercury',
    peakChartPositionUS: 3,
    certification: '4x Platinum',
    albumType: 'Studio',
    unitsSold: 4900000,
    url: 'https://www.rush.com/albums/moving-pictures/',
  },
  {
    title: 'Signals',
    artist: 'Rush',
    releaseDate: '9/9/1982',
    recordLabel: 'Mercury',
    peakChartPositionUS: 10,
    certification: 'Platinum',
    albumType: 'Studio',
    unitsSold: 1500000,
    url: 'https://www.rush.com/albums/signals/',
  },
  {
    title: 'Rush in Rio',
    artist: 'Rush',
    releaseDate: '10/21/2003',
    recordLabel: 'Anthem',
    peakChartPositionUS: 33,
    certification: 'Gold',
    albumType: 'Live',
    unitsSold: 600000,
    url: 'https://www.rush.com/albums/rush-in-rio/',
  },
  {
    title: 'Snakes & Arrows',
    artist: 'Rush',
    releaseDate: '5/1/2007',
    recordLabel: 'Atlantic',
    peakChartPositionUS: 3,
    certification: 'Gold',
    albumType: 'Studio',
    unitsSold: 750000,
    url: 'https://www.rush.com/albums/snakes-arrows/',
  },
  {
    title: 'R40 Live',
    artist: 'Rush',
    releaseDate: '11/20/2015',
    recordLabel: 'Anthem',
    peakChartPositionUS: 24,
    albumType: 'Live',
    unitsSold: 320000,
    url: 'https://www.rush.com/albums/r40-live/',
  },
  {
    title: 'The Spirit of Radio: Greatest Hits 1974–1987',
    artist: 'Rush',
    releaseDate: '2/11/2003',
    recordLabel: 'Anthem',
    peakChartPositionUS: 45,
    certification: 'Gold',
    albumType: 'Compilation',
    unitsSold: 800000,
  },
];
